baseurl = "/"
languageCode = "en-us"
title = "Hire This Guy!"
theme = "hugo-strata-theme"
# disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Marvin Bentley II"
	description = "Hire This Guy!"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "profile.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**HIRE THIS GUY!!!**"
		# The icons will be shown if you enter your username
		twitter = "truevox"
		github = "truevox"
		gitlab = "truevox"
		dribbble = ""
		facebook = "truevox"
		googleplus = "marvinbentleyii"
		flickr = ""
		linkedin = ""

		copyright = [
			"&copy; Marvin Bentley II",
			"Theme Design: [HTML5 UP](//html5up.net)",
		]


	[params.about]
		hide  = false
		title = "Marvin Bentley's Take Home Exercise for the Support Engineer Position at Netlify"
		content = "**Thanks for stopping in! The purpose of this site is to answer the following questions:** <br><br>Rank your 5 favorite, and least favorite, activities from this list: https://gist.github.com/fool/b0f254ff8c72a5765b6a9138249789d6 <br><br>What is your favorite thing about providing technical support? <br><br>What did you think of our service during the time you used it?  Be honest!  'it sucked' isn't a wrong answer unless you don't elaborate and provide some constructive criticism ;) <br><br>Tell about how you made your site and why you chose the tools you did.  Briefly explain a challenge you experienced in setting up this site and how you solved it. <br><br>Could you give us a suggestion to improve this test or the job posting? <br><br>Provide a link to documentation for a technical/developer-focused product, that you think are well done, and briefly explain why you think they are well done. <br><br>Why do you think SSL/HTTPS is important? <br><br>Explain, in a couple of paragraphs, what you think 2 major challenges around DNS configuration are for less-technical internet end-users <br><br>A customer writes in saying their 'site won't build'.  Compose your best short (2-paragraph) customer-facing answer without any additional data, that could be useful in the generic case but would also lead to a customer providing a more actionable response. <br><br>(optional/bonus) Can you set up a redirect from '/netlify/anything' to https://www.google.com/search?q=anything ? <br><br>**Each of the above questions is answered in a dedicated blog post on this site.**"


	[params.portfolio]
		hide  = true
		title = "Recent Work"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/01.jpg"
			thumb = "thumbs/01.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/02.jpg"
			thumb = "thumbs/02.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/03.jpg"
			thumb = "thumbs/03.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/04.jpg"
			thumb = "thumbs/04.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/05.jpg"
			thumb = "thumbs/05.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/06.jpg"
			thumb = "thumbs/06.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

	[params.recentposts]
		hide  = false
		title = "Recent blog posts"

	[params.contact]
		hide  = true
		title = "Get In Touch"
		content = "I look forward to speaking with you soon!"

		address = [
			"1 Starting Gate Ln",
			"Hinsdale, NH 03451",
			"United States"
		]
		phone = "802-275-4292"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "truevox@gmail.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 0
	
[[menu.main]]
    name = "About"
    url  = "about"
    weight = 5

[[menu.main]]
	name = "Blog"
	url  = "post/"
	weight = 10
